name: "My ESPHome"
slug: "my_esphome"
description: "User-controlled ESPHome version. Easily downgrade or upgrade."
version: "2025.10.5"
url: "https://github.com/shuricksumy/my-esphome-addon"
startup: services
boot: auto
arch:
  - aarch64
  - amd64
  - armv7

# ⚠️ The magic line:
image: "ghcr.io/esphome/esphome"
# HA will pull whatever TAG matches 'version' above.

ports:
  6052/tcp: null

homeassistant: 2023.0.0
options: {}
schema: {}
init: false