name: "My ESPHome"
slug: "my_esphome"
description: "User-controlled ESPHome version. Allows downgrading to 2025.10.5 or any other version."
version: "2025.10.5"
url: "https://github.com/shuricksumy/my-esphome-addon"
startup: services
boot: auto

arch:
  - amd64
  - aarch64
  - armv7
  - armhf

image: "ghcr.io/esphome/esphome"

ports:
  6052/tcp: 6052

options:
  esphome_version: "2025.10.5"

schema:
  esphome_version: str

init: false