name: "My ESPHome"
slug: "my_esphome"
description: "Custom pinned ESPHome version"
version: "2025.10.5"
url: "https://github.com/shuricksumy/my-esphome-addon"

startup: services
boot: auto

ingress: true
panel_title: "My ESPHome"
panel_icon: mdi:chip

arch:
  - amd64
  - aarch64
  - armv7
  - armhf

# Must use official hassio image, but pinned
image: ghcr.io/esphome/esphome-hassio:2025.10.5

ports:
  6052/tcp: null

init: false