name: "My ESPHome"
slug: "my_esphome"
description: "User-controlled ESPHome version with manual version selection."
version: !env_var esphome_version
url: "https://github.com/shuricksumy/my-esphome-addon"
startup: services
boot: auto

arch:
  - amd64
  - aarch64
  - armv7
  - armhf

options:
  esphome_version: "2025.10.5"

schema:
  esphome_version: str

image: "ghcr.io/esphome/esphome"

ports:
  6052/tcp: 6052

init: false