name: "My ESPHome"
slug: "my_esphome"
description: "User-controlled ESPHome version with manual version selection."
version: "2025.10.5"
url: "https://github.com/shuricksumy/my-esphome-addon"
startup: services
boot: auto

arch:
  - amd64
  - aarch64
  - armv7
  - armhf

image: "ghcr.io/esphome/esphome"

ports:
  6052/tcp: 6052

options: {}
schema: {}
init: false